### ISSUE TITLE
Can't pull the package dependency

### ISSUE THREAD

**Issue by ChrisMarxDev** [jicang/healywatch_reactive#76]
When trying to import the new version of the Watch SDK I am getting an error message:

```
Error on line 21, column 11: Invalid description in the "healy_watch_sdk" pubspec on the "flutter_plugin" dependency: "../flutter_plugin" is a relative path, but this isn't a local pubspec.
   ╷
21 │     path: ../flutter_plugin
   │           ^^^^^^^^^^^^^^^^^
   ╵
Running "flutter pub get" in healy-watch-app...                         
pub get failed (65;    ╵)

```

Because the `healy_package/pubspec.yaml` imports the new `flutter_plugin` via relative path and not with a github dependency.

The dependency I used to import the Watch SDK is the following:

```yaml
dependencies:
  healy_watch_sdk:
    git:
      url: https://github.com/jicang/healywatch_reactive.git
      ref: 0fdfc492db0e23317c589214548a20b5afb1d177
      path: healy_package
```
